export type ScreenArea = "public" | "partner" | "chef" | "admin";

export type ScreenDefinition = {
  id: string;
  title: string;
  path: string;
  area: ScreenArea;
  category: string;
  summary: string;
  keywords: string[];
};

export const screenCatalog: ScreenDefinition[] = [
  {
    id: "homepage",
    title: "Homepage",
    path: "/",
    area: "public",
    category: "Discovery & Entry",
    summary: "Landing page introducing curated Dubai dining discovery.",
    keywords: ["discover", "hero", "featured"],
  },
  {
    id: "search-results",
    title: "Search Results Page",
    path: "/search/results",
    area: "public",
    category: "Discovery & Entry",
    summary: "Result list with sorting, pagination, and quick actions.",
    keywords: ["search", "results", "sorting"],
  },
  {
    id: "search-suggestions",
    title: "Search Suggestions Dropdown",
    path: "/search/suggestions",
    area: "public",
    category: "Discovery & Entry",
    summary: "Typeahead dropdown for dishes, restaurants, and neighborhoods.",
    keywords: ["search", "suggestions", "dropdown"],
  },
  {
    id: "filter-panel",
    title: "Filter Panel",
    path: "/search/filters",
    area: "public",
    category: "Discovery & Entry",
    summary: "Sidebar and modal filter controls with cuisine, budget, and rating.",
    keywords: ["filters", "sidebar", "modal"],
  },
  {
    id: "map-view",
    title: "Map View Page",
    path: "/map",
    area: "public",
    category: "Discovery & Entry",
    summary: "Interactive map first experience for location based discovery.",
    keywords: ["map", "pins", "location"],
  },
  {
    id: "restaurants-location",
    title: "Restaurants in Location Page",
    path: "/restaurants/location/downtown-dubai",
    area: "public",
    category: "SEO Programmatic",
    summary: "Template for location based dining SEO pages.",
    keywords: ["seo", "location", "template"],
  },
  {
    id: "cuisine-category",
    title: "Cuisine Category Page",
    path: "/restaurants/cuisine/japanese",
    area: "public",
    category: "SEO Programmatic",
    summary: "Template for cuisine specific organic landing pages.",
    keywords: ["seo", "cuisine", "category"],
  },
  {
    id: "budget-based",
    title: "Budget-Based Page",
    path: "/restaurants/budget/aed-200",
    area: "public",
    category: "SEO Programmatic",
    summary: "Template for budget bands and pricing based navigation.",
    keywords: ["budget", "price", "seo"],
  },
  {
    id: "occasion-based",
    title: "Occasion-Based Page",
    path: "/restaurants/occasion/date-night",
    area: "public",
    category: "SEO Programmatic",
    summary: "Template for intent driven occasion pages.",
    keywords: ["occasion", "intent", "seo"],
  },
  {
    id: "cuisine-location",
    title: "Cuisine + Location Page",
    path: "/restaurants/cuisine/japanese/location/downtown-dubai",
    area: "public",
    category: "SEO Programmatic",
    summary: "Template combining cuisine and neighborhood facets.",
    keywords: ["seo", "facet", "location"],
  },
  {
    id: "restaurant-listing",
    title: "Restaurant Listing Page",
    path: "/restaurants",
    area: "public",
    category: "Restaurant Experience",
    summary: "Browsable catalog of restaurants with preview cards.",
    keywords: ["listing", "catalog", "restaurants"],
  },
  {
    id: "restaurant-detail",
    title: "Restaurant Detail Page",
    path: "/restaurants/al-safa-club",
    area: "public",
    category: "Restaurant Experience",
    summary: "Full profile showing overview, highlights, and details.",
    keywords: ["detail", "hero", "overview"],
  },
  {
    id: "restaurant-menu",
    title: "Restaurant Menu Page",
    path: "/restaurants/al-safa-club/menu",
    area: "public",
    category: "Restaurant Experience",
    summary: "Menu browsing with sections and signature dishes.",
    keywords: ["menu", "dishes", "pricing"],
  },
  {
    id: "restaurant-reviews",
    title: "Restaurant Reviews Page",
    path: "/restaurants/al-safa-club/reviews",
    area: "public",
    category: "Restaurant Experience",
    summary: "User generated ratings and review feed.",
    keywords: ["reviews", "ratings", "ugc"],
  },
  {
    id: "restaurant-gallery",
    title: "Restaurant Gallery",
    path: "/restaurants/al-safa-club/gallery",
    area: "public",
    category: "Restaurant Experience",
    summary: "Photo and video gallery experience.",
    keywords: ["gallery", "photos", "videos"],
  },
  {
    id: "chef-listing",
    title: "Chef Listing Page",
    path: "/chefs",
    area: "public",
    category: "Chef System",
    summary: "Directory of chefs with cuisine specialties.",
    keywords: ["chefs", "directory", "profiles"],
  },
  {
    id: "chef-profile",
    title: "Chef Profile Page",
    path: "/chefs/amina-haddad",
    area: "public",
    category: "Chef System",
    summary: "Chef biography, achievements, and cuisine style.",
    keywords: ["chef", "profile", "bio"],
  },
  {
    id: "chef-restaurants",
    title: "Chef to Restaurants Page",
    path: "/chefs/amina-haddad/restaurants",
    area: "public",
    category: "Chef System",
    summary: "Linked restaurant roster for each chef profile.",
    keywords: ["chef", "restaurants", "links"],
  },
  {
    id: "booking-widget",
    title: "Booking Widget",
    path: "/booking/widget",
    area: "public",
    category: "Booking System",
    summary: "Embeddable reservation widget component.",
    keywords: ["booking", "widget", "component"],
  },
  {
    id: "booking-page",
    title: "Booking Page",
    path: "/booking",
    area: "public",
    category: "Booking System",
    summary: "Primary reservation form and availability controls.",
    keywords: ["booking", "form", "reservation"],
  },
  {
    id: "booking-confirmation",
    title: "Booking Confirmation Page",
    path: "/booking/confirmation",
    area: "public",
    category: "Booking System",
    summary: "Success state with reservation details and next steps.",
    keywords: ["booking", "success", "confirmation"],
  },
  {
    id: "booking-error",
    title: "Booking Failure/Error Page",
    path: "/booking/error",
    area: "public",
    category: "Booking System",
    summary: "Failure state and guided recovery options.",
    keywords: ["booking", "error", "retry"],
  },
  {
    id: "booking-modification",
    title: "Booking Modification Page",
    path: "/booking/modify",
    area: "public",
    category: "Booking System",
    summary: "Change date, party size, and special requests.",
    keywords: ["booking", "edit", "reschedule"],
  },
  {
    id: "booking-cancellation",
    title: "Booking Cancellation Flow",
    path: "/booking/cancel",
    area: "public",
    category: "Booking System",
    summary: "Cancellation confirmation and retention prompts.",
    keywords: ["booking", "cancel", "flow"],
  },
  {
    id: "signup",
    title: "Sign Up Page",
    path: "/signup",
    area: "public",
    category: "User Account",
    summary: "User account creation and onboarding fields.",
    keywords: ["auth", "signup", "account"],
  },
  {
    id: "login",
    title: "Login Page",
    path: "/login",
    area: "public",
    category: "User Account",
    summary: "Authentication screen for returning users.",
    keywords: ["auth", "login", "security"],
  },
  {
    id: "forgot-password",
    title: "Forgot Password Page",
    path: "/forgot-password",
    area: "public",
    category: "User Account",
    summary: "Password reset initiation and recovery messaging.",
    keywords: ["auth", "password", "reset"],
  },
  {
    id: "user-profile",
    title: "User Profile Page",
    path: "/account/profile",
    area: "public",
    category: "User Account",
    summary: "Personal account overview and preferences.",
    keywords: ["profile", "account", "settings"],
  },
  {
    id: "edit-profile",
    title: "Edit Profile Page",
    path: "/account/profile/edit",
    area: "public",
    category: "User Account",
    summary: "Editable user details, cuisine interests, and tags.",
    keywords: ["profile", "edit", "preferences"],
  },
  {
    id: "favorites",
    title: "Favorites Page",
    path: "/account/favorites",
    area: "public",
    category: "User Account",
    summary: "Saved restaurants and collections.",
    keywords: ["favorites", "saved", "collections"],
  },
  {
    id: "booking-history",
    title: "Booking History Page",
    path: "/account/bookings",
    area: "public",
    category: "User Account",
    summary: "Past and upcoming reservations timeline.",
    keywords: ["bookings", "history", "timeline"],
  },
  {
    id: "my-reviews",
    title: "My Reviews Page",
    path: "/account/reviews",
    area: "public",
    category: "User Account",
    summary: "User authored review management.",
    keywords: ["reviews", "author", "account"],
  },
  {
    id: "notifications",
    title: "Notifications Page",
    path: "/account/notifications",
    area: "public",
    category: "User Account",
    summary: "Alerts for bookings, promotions, and updates.",
    keywords: ["notifications", "alerts", "messages"],
  },
  {
    id: "blog-listing",
    title: "Blog Listing Page",
    path: "/blog",
    area: "public",
    category: "Content & SEO",
    summary: "Editorial index with featured stories.",
    keywords: ["blog", "content", "seo"],
  },
  {
    id: "blog-article",
    title: "Blog Article Page",
    path: "/blog/the-rise-of-desert-farm-to-table",
    area: "public",
    category: "Content & SEO",
    summary: "Long form article page with share and related links.",
    keywords: ["blog", "article", "editorial"],
  },
  {
    id: "author-page",
    title: "Author Page",
    path: "/authors/lina-saeed",
    area: "public",
    category: "Content & SEO",
    summary: "Author bio and published article archive.",
    keywords: ["author", "bio", "posts"],
  },
  {
    id: "about",
    title: "About Page",
    path: "/about",
    area: "public",
    category: "Static Pages",
    summary: "Mission, story, and product positioning.",
    keywords: ["about", "story", "mission"],
  },
  {
    id: "contact",
    title: "Contact Page",
    path: "/contact",
    area: "public",
    category: "Static Pages",
    summary: "Support contacts and inquiry channels.",
    keywords: ["contact", "support", "help"],
  },
  {
    id: "faq",
    title: "FAQ Page",
    path: "/faq",
    area: "public",
    category: "Static Pages",
    summary: "Frequently asked questions and quick answers.",
    keywords: ["faq", "help", "guides"],
  },
  {
    id: "privacy-policy",
    title: "Privacy Policy",
    path: "/privacy",
    area: "public",
    category: "Static Pages",
    summary: "Data privacy, retention, and rights documentation.",
    keywords: ["privacy", "policy", "legal"],
  },
  {
    id: "terms-of-service",
    title: "Terms of Service",
    path: "/terms",
    area: "public",
    category: "Static Pages",
    summary: "Service terms, acceptable use, and limitations.",
    keywords: ["terms", "service", "legal"],
  },
  {
    id: "partner-login",
    title: "Partner Login Page",
    path: "/partner/login",
    area: "partner",
    category: "Partner Auth",
    summary: "Restaurant partner authentication page.",
    keywords: ["partner", "login", "auth"],
  },
  {
    id: "partner-registration",
    title: "Partner Registration Page",
    path: "/partner/register",
    area: "partner",
    category: "Partner Auth",
    summary: "Restaurant onboarding and registration flow.",
    keywords: ["partner", "register", "onboarding"],
  },
  {
    id: "partner-dashboard",
    title: "Dashboard Overview",
    path: "/partner/dashboard",
    area: "partner",
    category: "Partner Dashboard",
    summary: "Performance summary for partner operations.",
    keywords: ["dashboard", "overview", "partner"],
  },
  {
    id: "partner-analytics",
    title: "Analytics Page",
    path: "/partner/dashboard/analytics",
    area: "partner",
    category: "Partner Dashboard",
    summary: "Traffic and reservation analytics for partners.",
    keywords: ["analytics", "partner", "insights"],
  },
  {
    id: "partner-profile-editor",
    title: "Restaurant Profile Editor",
    path: "/partner/listing/profile",
    area: "partner",
    category: "Listing Management",
    summary: "Edit profile details for partner restaurant listings.",
    keywords: ["partner", "listing", "editor"],
  },
  {
    id: "partner-menu-upload",
    title: "Menu Upload Page",
    path: "/partner/listing/menu-upload",
    area: "partner",
    category: "Listing Management",
    summary: "Upload and manage menu files for listings.",
    keywords: ["menu", "upload", "partner"],
  },
  {
    id: "partner-media-upload",
    title: "Media Upload Page (Partner)",
    path: "/partner/listing/media-upload",
    area: "partner",
    category: "Listing Management",
    summary: "Upload image and video assets for partner pages.",
    keywords: ["media", "upload", "assets"],
  },
  {
    id: "partner-bookings-list",
    title: "Bookings List Page",
    path: "/partner/bookings",
    area: "partner",
    category: "Booking Management",
    summary: "Reservation queue and table assignment management.",
    keywords: ["bookings", "queue", "partner"],
  },
  {
    id: "partner-booking-detail",
    title: "Booking Detail Page",
    path: "/partner/bookings/bkg-1042",
    area: "partner",
    category: "Booking Management",
    summary: "Detailed booking record with guest notes.",
    keywords: ["booking", "detail", "guest"],
  },
  {
    id: "partner-subscription-plans",
    title: "Subscription Plans Page",
    path: "/partner/monetization/plans",
    area: "partner",
    category: "Monetization",
    summary: "Plan comparison and subscription selection.",
    keywords: ["plans", "subscription", "pricing"],
  },
  {
    id: "partner-billing",
    title: "Billing Page",
    path: "/partner/monetization/billing",
    area: "partner",
    category: "Monetization",
    summary: "Billing methods, invoices, and payment history.",
    keywords: ["billing", "payments", "invoices"],
  },
  {
    id: "partner-upgrade-plan",
    title: "Upgrade Plan Page",
    path: "/partner/monetization/upgrade",
    area: "partner",
    category: "Monetization",
    summary: "Upgrade workflow and feature unlocks.",
    keywords: ["upgrade", "plan", "features"],
  },
  {
    id: "partner-featured-listing",
    title: "Featured Listing Setup Page",
    path: "/partner/promotions/featured",
    area: "partner",
    category: "Promotions",
    summary: "Configure promoted placements and priorities.",
    keywords: ["featured", "listing", "promotion"],
  },
  {
    id: "partner-promotions-campaign",
    title: "Promotions / Campaign Page",
    path: "/partner/promotions/campaigns",
    area: "partner",
    category: "Promotions",
    summary: "Campaign planning and promo performance panel.",
    keywords: ["campaign", "promotion", "partner"],
  },
  {
    id: "chef-login",
    title: "Chef Login Page",
    path: "/chef/login",
    area: "chef",
    category: "Chef Dashboard",
    summary: "Chef authentication for dashboard access.",
    keywords: ["chef", "auth", "login"],
  },
  {
    id: "chef-dashboard",
    title: "Chef Dashboard Overview",
    path: "/chef/dashboard",
    area: "chef",
    category: "Chef Dashboard",
    summary: "Chef performance overview and content snapshots.",
    keywords: ["chef", "dashboard", "overview"],
  },
  {
    id: "chef-profile-editor",
    title: "Chef Profile Editor",
    path: "/chef/dashboard/profile",
    area: "chef",
    category: "Chef Dashboard",
    summary: "Edit chef profile, bio, and specialties.",
    keywords: ["chef", "profile", "editor"],
  },
  {
    id: "chef-media-upload",
    title: "Media Upload Page (Chef)",
    path: "/chef/dashboard/media",
    area: "chef",
    category: "Chef Dashboard",
    summary: "Upload chef story visuals and highlights.",
    keywords: ["chef", "media", "upload"],
  },
  {
    id: "chef-linked-restaurants",
    title: "Linked Restaurants Manager",
    path: "/chef/dashboard/restaurants",
    area: "chef",
    category: "Chef Dashboard",
    summary: "Manage restaurant affiliations and featured venues.",
    keywords: ["chef", "restaurants", "manager"],
  },
  {
    id: "admin-dashboard",
    title: "Admin Dashboard",
    path: "/admin",
    area: "admin",
    category: "Core Admin",
    summary: "System wide administration command center.",
    keywords: ["admin", "dashboard", "system"],
  },
  {
    id: "admin-restaurant-approval",
    title: "Restaurant Approval Page",
    path: "/admin/restaurants/approval",
    area: "admin",
    category: "Restaurant Control",
    summary: "Approval queue for new restaurant submissions.",
    keywords: ["admin", "restaurants", "approval"],
  },
  {
    id: "admin-restaurant-management",
    title: "Restaurant Management Page",
    path: "/admin/restaurants/management",
    area: "admin",
    category: "Restaurant Control",
    summary: "Manage restaurant records and listing status.",
    keywords: ["admin", "restaurants", "management"],
  },
  {
    id: "admin-chef-approval",
    title: "Chef Approval Page",
    path: "/admin/chefs/approval",
    area: "admin",
    category: "Chef Control",
    summary: "Review and approve chef verification requests.",
    keywords: ["admin", "chefs", "approval"],
  },
  {
    id: "admin-chef-management",
    title: "Chef Management Page",
    path: "/admin/chefs/management",
    area: "admin",
    category: "Chef Control",
    summary: "Manage chef profiles and ranking visibility.",
    keywords: ["admin", "chefs", "management"],
  },
  {
    id: "admin-user-management",
    title: "User Management Page",
    path: "/admin/users",
    area: "admin",
    category: "User Management",
    summary: "User account moderation and enforcement actions.",
    keywords: ["admin", "users", "management"],
  },
  {
    id: "admin-reviews-moderation",
    title: "Reviews Moderation Page",
    path: "/admin/moderation/reviews",
    area: "admin",
    category: "Content Moderation",
    summary: "Moderate review content and policy breaches.",
    keywords: ["admin", "reviews", "moderation"],
  },
  {
    id: "admin-blog-management",
    title: "Blog Management Page",
    path: "/admin/moderation/blog",
    area: "admin",
    category: "Content Moderation",
    summary: "Publish, unpublish, and schedule editorial content.",
    keywords: ["admin", "blog", "moderation"],
  },
  {
    id: "admin-revenue-dashboard",
    title: "Revenue Dashboard",
    path: "/admin/revenue",
    area: "admin",
    category: "Revenue & Ads",
    summary: "Revenue trends, payouts, and monetization health.",
    keywords: ["admin", "revenue", "finance"],
  },
  {
    id: "admin-ad-management",
    title: "Ad Management Page",
    path: "/admin/ads",
    area: "admin",
    category: "Revenue & Ads",
    summary: "Manage ad inventory and campaign eligibility.",
    keywords: ["admin", "ads", "campaigns"],
  },
  {
    id: "admin-sponsored-listings",
    title: "Sponsored Listings Control",
    path: "/admin/sponsored-listings",
    area: "admin",
    category: "Revenue & Ads",
    summary: "Control sponsored listing placements and rules.",
    keywords: ["admin", "sponsored", "listings"],
  },
];

export const screenCatalogByPath = new Map(
  screenCatalog.map((screen) => [screen.path, screen]),
);

export const screenCatalogById = new Map(
  screenCatalog.map((screen) => [screen.id, screen]),
);

export const screenPaths = screenCatalog.map((screen) => screen.path);

export function buildPathFromSlug(slug?: string[]): string {
  if (!slug || slug.length === 0) {
    return "/";
  }

  return `/${slug.join("/")}`;
}

export function resolveScreenByPath(path: string): ScreenDefinition | undefined {
  const normalized = path === "/" ? "/" : path.replace(/\/+$/, "");
  return screenCatalogByPath.get(normalized);
}

export function formatArea(area: ScreenArea): string {
  if (area === "public") {
    return "Public User";
  }

  if (area === "partner") {
    return "Restaurant Partner";
  }

  if (area === "chef") {
    return "Chef Dashboard";
  }

  return "Admin Panel";
}
